/*
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class BotWebModule extends AbstractBotWebModule {
}
