/*
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.web;

import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;

import com.google.inject.Binder;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class BotWebModule extends AbstractBotWebModule {
	
	
	public void configure(Binder binder) {
		binder.bind(IServerResourceHandler.class).to(FileResourceHandler.class);
		binder.bind(IResourceBaseProvider.class).toInstance(
				new ResourceBaseProviderImpl("."));
		super.configure(binder);
	}
	
	
}
