/*
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.web;

import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;

import com.google.inject.Binder;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class BotWebModule extends AbstractBotWebModule {
	public FileResourceHandler bindIServerResourceHandler()  {
		// your own impl here
		FileResourceHandler handler = new FileResourceHandler();
		return handler;
	}
	
	// only needed for FileResourceHandler
	public void configureIResourceBaseProvider(Binder binder) {
		binder.bind(IResourceBaseProvider.class).toInstance(
		new ResourceBaseProviderImpl("."));
	}
}
