/*
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BotUiModule extends AbstractBotUiModule {

	public BotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
