/*
 * generated by Xtext 2.22.0
 */
package org.xtext.botGenerator.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.botGenerator.dsl.ui.internal.DslActivator;

public class BotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.botGenerator.Bot");
	}

}
