/*
 * generated by Xtext 2.25.0
 */
package org.xtext.botGenerator.ui.tests;

import botGenerator.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.botGenerator.Bot");
	}

}
