/**
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.botGenerator.tests.BotInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(BotInjectorProvider.class)
@SuppressWarnings("all")
public class BotParsingTest {
  @Inject
  private /* ParseHelper<Bot> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field BotParsingTest.parseHelper refers to the missing type Bot"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
