/*
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.botGenerator.ide.contentassist.antlr.internal.InternalBotParser;
import org.xtext.botGenerator.services.BotGrammarAccess;

public class BotParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BotGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BotGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getTokenAccess().getAlternatives(), "rule__Token__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getTransitionAccess().getTargetAlternatives_2_1_0(), "rule__Transition__TargetAlternatives_2_1_0");
			builder.put(grammarAccess.getIntentInputAccess().getAlternatives(), "rule__IntentInput__Alternatives");
			builder.put(grammarAccess.getTrainingPhraseAccess().getTokensAlternatives_1_0(), "rule__TrainingPhrase__TokensAlternatives_1_0");
			builder.put(grammarAccess.getParameterAccess().getAlternatives_3(), "rule__Parameter__Alternatives_3");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEntityInputAccess().getAlternatives(), "rule__EntityInput__Alternatives");
			builder.put(grammarAccess.getCompositeInputAccess().getExpresionAlternatives_3_0(), "rule__CompositeInput__ExpresionAlternatives_3_0");
			builder.put(grammarAccess.getTextInputHttpResponseAccess().getTokensAlternatives_0(), "rule__TextInputHttpResponse__TokensAlternatives_0");
			builder.put(grammarAccess.getTextInputTextAccess().getTokensAlternatives_0(), "rule__TextInputText__TokensAlternatives_0");
			builder.put(grammarAccess.getDataAccess().getValueAlternatives_2_0(), "rule__Data__ValueAlternatives_2_0");
			builder.put(grammarAccess.getDefaultEntityAccess().getAlternatives(), "rule__DefaultEntity__Alternatives");
			builder.put(grammarAccess.getHTTPReturnTypeAccess().getAlternatives(), "rule__HTTPReturnType__Alternatives");
			builder.put(grammarAccess.getLanguageAccess().getAlternatives(), "rule__Language__Alternatives");
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getMethodAccess().getAlternatives(), "rule__Method__Alternatives");
			builder.put(grammarAccess.getBotAccess().getGroup(), "rule__Bot__Group__0");
			builder.put(grammarAccess.getBotAccess().getGroup_4(), "rule__Bot__Group_4__0");
			builder.put(grammarAccess.getBotAccess().getGroup_9(), "rule__Bot__Group_9__0");
			builder.put(grammarAccess.getBotAccess().getGroup_10(), "rule__Bot__Group_10__0");
			builder.put(grammarAccess.getBotAccess().getGroup_13(), "rule__Bot__Group_13__0");
			builder.put(grammarAccess.getIntentAccess().getGroup(), "rule__Intent__Group__0");
			builder.put(grammarAccess.getIntentAccess().getGroup_4(), "rule__Intent__Group_4__0");
			builder.put(grammarAccess.getIntentAccess().getGroup_4_1(), "rule__Intent__Group_4_1__0");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getGroup(), "rule__IntentLanguageInputs__Group__0");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getGroup_1(), "rule__IntentLanguageInputs__Group_1__0");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getGroup_4(), "rule__IntentLanguageInputs__Group_4__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_2(), "rule__Transition__Group_2__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup_2(), "rule__State__Group_2__0");
			builder.put(grammarAccess.getStateAccess().getGroup_3(), "rule__State__Group_3__0");
			builder.put(grammarAccess.getState2Access().getGroup(), "rule__State2__Group__0");
			builder.put(grammarAccess.getState2Access().getGroup_2(), "rule__State2__Group_2__0");
			builder.put(grammarAccess.getState2Access().getGroup_4(), "rule__State2__Group_4__0");
			builder.put(grammarAccess.getTrainingPhraseAccess().getGroup(), "rule__TrainingPhrase__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_4(), "rule__Parameter__Group_4__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_5(), "rule__Parameter__Group_5__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_6(), "rule__Parameter__Group_6__0");
			builder.put(grammarAccess.getParameter2Access().getGroup(), "rule__Parameter2__Group__0");
			builder.put(grammarAccess.getPromptLanguageAccess().getGroup(), "rule__PromptLanguage__Group__0");
			builder.put(grammarAccess.getPromptLanguageAccess().getGroup_1(), "rule__PromptLanguage__Group_1__0");
			builder.put(grammarAccess.getPromptLanguageAccess().getGroup_4(), "rule__PromptLanguage__Group_4__0");
			builder.put(grammarAccess.getEntityTokenAccess().getGroup(), "rule__EntityToken__Group__0");
			builder.put(grammarAccess.getParameterTokenAccess().getGroup(), "rule__ParameterToken__Group__0");
			builder.put(grammarAccess.getParameterRefenceTokenAccess().getGroup(), "rule__ParameterRefenceToken__Group__0");
			builder.put(grammarAccess.getHTTPRequestTokenAccess().getGroup(), "rule__HTTPRequestToken__Group__0");
			builder.put(grammarAccess.getHTTPRequestTokenAccess().getGroup_2(), "rule__HTTPRequestToken__Group_2__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getLanguageInputAccess().getGroup(), "rule__LanguageInput__Group__0");
			builder.put(grammarAccess.getLanguageInputAccess().getGroup_0(), "rule__LanguageInput__Group_0__0");
			builder.put(grammarAccess.getLanguageInputAccess().getGroup_2(), "rule__LanguageInput__Group_2__0");
			builder.put(grammarAccess.getRegexInputAccess().getGroup(), "rule__RegexInput__Group__0");
			builder.put(grammarAccess.getCompositeInputAccess().getGroup(), "rule__CompositeInput__Group__0");
			builder.put(grammarAccess.getSimpleInputAccess().getGroup(), "rule__SimpleInput__Group__0");
			builder.put(grammarAccess.getSimpleInputAccess().getGroup_4(), "rule__SimpleInput__Group_4__0");
			builder.put(grammarAccess.getSimpleInputAccess().getGroup_4_2(), "rule__SimpleInput__Group_4_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
			builder.put(grammarAccess.getTextLanguageInputAccess().getGroup(), "rule__TextLanguageInput__Group__0");
			builder.put(grammarAccess.getTextLanguageInputAccess().getGroup_0(), "rule__TextLanguageInput__Group_0__0");
			builder.put(grammarAccess.getTextLanguageInputAccess().getGroup_0_1(), "rule__TextLanguageInput__Group_0_1__0");
			builder.put(grammarAccess.getTextLanguageInputAccess().getGroup_3(), "rule__TextLanguageInput__Group_3__0");
			builder.put(grammarAccess.getHTTPResponseAccess().getGroup(), "rule__HTTPResponse__Group__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup(), "rule__HTTPRequest__Group__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup_9(), "rule__HTTPRequest__Group_9__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup_10(), "rule__HTTPRequest__Group_10__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup_10_3(), "rule__HTTPRequest__Group_10_3__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup_11(), "rule__HTTPRequest__Group_11__0");
			builder.put(grammarAccess.getHTTPRequestAccess().getGroup_11_3(), "rule__HTTPRequest__Group_11_3__0");
			builder.put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getGroup(), "rule__TextLanguageInputHttpResponse__Group__0");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getGroup_1(), "rule__TextLanguageInputHttpResponse__Group_1__0");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getGroup_4(), "rule__TextLanguageInputHttpResponse__Group_4__0");
			builder.put(grammarAccess.getKeyValueAccess().getGroup(), "rule__KeyValue__Group__0");
			builder.put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
			builder.put(grammarAccess.getBotAccess().getNameAssignment_1(), "rule__Bot__NameAssignment_1");
			builder.put(grammarAccess.getBotAccess().getLanguagesAssignment_3(), "rule__Bot__LanguagesAssignment_3");
			builder.put(grammarAccess.getBotAccess().getLanguagesAssignment_4_1(), "rule__Bot__LanguagesAssignment_4_1");
			builder.put(grammarAccess.getBotAccess().getIntentsAssignment_7(), "rule__Bot__IntentsAssignment_7");
			builder.put(grammarAccess.getBotAccess().getIntentsAssignment_8(), "rule__Bot__IntentsAssignment_8");
			builder.put(grammarAccess.getBotAccess().getEntitiesAssignment_9_2(), "rule__Bot__EntitiesAssignment_9_2");
			builder.put(grammarAccess.getBotAccess().getEntitiesAssignment_9_3(), "rule__Bot__EntitiesAssignment_9_3");
			builder.put(grammarAccess.getBotAccess().getActionsAssignment_10_2(), "rule__Bot__ActionsAssignment_10_2");
			builder.put(grammarAccess.getBotAccess().getActionsAssignment_10_3(), "rule__Bot__ActionsAssignment_10_3");
			builder.put(grammarAccess.getBotAccess().getFlowsAssignment_13_1(), "rule__Bot__FlowsAssignment_13_1");
			builder.put(grammarAccess.getIntentAccess().getNameAssignment_0(), "rule__Intent__NameAssignment_0");
			builder.put(grammarAccess.getIntentAccess().getFallbackIntentAssignment_1(), "rule__Intent__FallbackIntentAssignment_1");
			builder.put(grammarAccess.getIntentAccess().getInputsAssignment_3(), "rule__Intent__InputsAssignment_3");
			builder.put(grammarAccess.getIntentAccess().getParametersAssignment_4_1_0(), "rule__Intent__ParametersAssignment_4_1_0");
			builder.put(grammarAccess.getIntentAccess().getParametersAssignment_4_1_1(), "rule__Intent__ParametersAssignment_4_1_1");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getLanguageAssignment_1_1(), "rule__IntentLanguageInputs__LanguageAssignment_1_1");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getInputsAssignment_3(), "rule__IntentLanguageInputs__InputsAssignment_3");
			builder.put(grammarAccess.getIntentLanguageInputsAccess().getInputsAssignment_4_1(), "rule__IntentLanguageInputs__InputsAssignment_4_1");
			builder.put(grammarAccess.getTransitionAccess().getIntentAssignment_1(), "rule__Transition__IntentAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getTargetAssignment_2_1(), "rule__Transition__TargetAssignment_2_1");
			builder.put(grammarAccess.getStateAccess().getActionsAssignment_1(), "rule__State__ActionsAssignment_1");
			builder.put(grammarAccess.getStateAccess().getActionsAssignment_2_1(), "rule__State__ActionsAssignment_2_1");
			builder.put(grammarAccess.getStateAccess().getOutcomingAssignment_3_1(), "rule__State__OutcomingAssignment_3_1");
			builder.put(grammarAccess.getState2Access().getActionsAssignment_1(), "rule__State2__ActionsAssignment_1");
			builder.put(grammarAccess.getState2Access().getActionsAssignment_2_1(), "rule__State2__ActionsAssignment_2_1");
			builder.put(grammarAccess.getState2Access().getOutcomingAssignment_4_1(), "rule__State2__OutcomingAssignment_4_1");
			builder.put(grammarAccess.getTrainingPhraseAccess().getTokensAssignment_1(), "rule__TrainingPhrase__TokensAssignment_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_0(), "rule__Parameter__NameAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getEntityAssignment_3_0(), "rule__Parameter__EntityAssignment_3_0");
			builder.put(grammarAccess.getParameterAccess().getDefaultEntityAssignment_3_1(), "rule__Parameter__DefaultEntityAssignment_3_1");
			builder.put(grammarAccess.getParameterAccess().getRequiredAssignment_4_1(), "rule__Parameter__RequiredAssignment_4_1");
			builder.put(grammarAccess.getParameterAccess().getPromptsAssignment_5_1(), "rule__Parameter__PromptsAssignment_5_1");
			builder.put(grammarAccess.getParameterAccess().getIsListAssignment_6_1(), "rule__Parameter__IsListAssignment_6_1");
			builder.put(grammarAccess.getParameter2Access().getNameAssignment_0(), "rule__Parameter2__NameAssignment_0");
			builder.put(grammarAccess.getPromptLanguageAccess().getLanguageAssignment_1_1(), "rule__PromptLanguage__LanguageAssignment_1_1");
			builder.put(grammarAccess.getPromptLanguageAccess().getPromptsAssignment_3(), "rule__PromptLanguage__PromptsAssignment_3");
			builder.put(grammarAccess.getPromptLanguageAccess().getPromptsAssignment_4_1(), "rule__PromptLanguage__PromptsAssignment_4_1");
			builder.put(grammarAccess.getLiteralAccess().getTextAssignment(), "rule__Literal__TextAssignment");
			builder.put(grammarAccess.getEntityTokenAccess().getEntityAssignment_2(), "rule__EntityToken__EntityAssignment_2");
			builder.put(grammarAccess.getParameterTokenAccess().getParameterAssignment_1(), "rule__ParameterToken__ParameterAssignment_1");
			builder.put(grammarAccess.getParameterRefenceTokenAccess().getTextReferenceAssignment_1(), "rule__ParameterRefenceToken__TextReferenceAssignment_1");
			builder.put(grammarAccess.getParameterRefenceTokenAccess().getParameterAssignment_4(), "rule__ParameterRefenceToken__ParameterAssignment_4");
			builder.put(grammarAccess.getHTTPRequestTokenAccess().getTypeAssignment_1(), "rule__HTTPRequestToken__TypeAssignment_1");
			builder.put(grammarAccess.getHTTPRequestTokenAccess().getDataKeyAssignment_2_1(), "rule__HTTPRequestToken__DataKeyAssignment_2_1");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getInputsAssignment_3(), "rule__Entity__InputsAssignment_3");
			builder.put(grammarAccess.getLanguageInputAccess().getLanguageAssignment_0_2(), "rule__LanguageInput__LanguageAssignment_0_2");
			builder.put(grammarAccess.getLanguageInputAccess().getInputsAssignment_2_0(), "rule__LanguageInput__InputsAssignment_2_0");
			builder.put(grammarAccess.getLanguageInputAccess().getInputsAssignment_2_1(), "rule__LanguageInput__InputsAssignment_2_1");
			builder.put(grammarAccess.getRegexInputAccess().getExpresionAssignment_3(), "rule__RegexInput__ExpresionAssignment_3");
			builder.put(grammarAccess.getCompositeInputAccess().getExpresionAssignment_3(), "rule__CompositeInput__ExpresionAssignment_3");
			builder.put(grammarAccess.getSimpleInputAccess().getNameAssignment_3(), "rule__SimpleInput__NameAssignment_3");
			builder.put(grammarAccess.getSimpleInputAccess().getValuesAssignment_4_1(), "rule__SimpleInput__ValuesAssignment_4_1");
			builder.put(grammarAccess.getSimpleInputAccess().getValuesAssignment_4_2_1(), "rule__SimpleInput__ValuesAssignment_4_2_1");
			builder.put(grammarAccess.getTextAccess().getNameAssignment_2(), "rule__Text__NameAssignment_2");
			builder.put(grammarAccess.getTextAccess().getInputsAssignment_4(), "rule__Text__InputsAssignment_4");
			builder.put(grammarAccess.getTextLanguageInputAccess().getLanguageAssignment_0_1_1(), "rule__TextLanguageInput__LanguageAssignment_0_1_1");
			builder.put(grammarAccess.getTextLanguageInputAccess().getInputsAssignment_2(), "rule__TextLanguageInput__InputsAssignment_2");
			builder.put(grammarAccess.getTextLanguageInputAccess().getInputsAssignment_3_1(), "rule__TextLanguageInput__InputsAssignment_3_1");
			builder.put(grammarAccess.getHTTPResponseAccess().getNameAssignment_1(), "rule__HTTPResponse__NameAssignment_1");
			builder.put(grammarAccess.getHTTPResponseAccess().getHTTPRequestAssignment_4(), "rule__HTTPResponse__HTTPRequestAssignment_4");
			builder.put(grammarAccess.getHTTPResponseAccess().getInputsAssignment_6(), "rule__HTTPResponse__InputsAssignment_6");
			builder.put(grammarAccess.getHTTPRequestAccess().getMethodAssignment_2(), "rule__HTTPRequest__MethodAssignment_2");
			builder.put(grammarAccess.getHTTPRequestAccess().getNameAssignment_3(), "rule__HTTPRequest__NameAssignment_3");
			builder.put(grammarAccess.getHTTPRequestAccess().getURLAssignment_7(), "rule__HTTPRequest__URLAssignment_7");
			builder.put(grammarAccess.getHTTPRequestAccess().getBasicAuthAssignment_9_2(), "rule__HTTPRequest__BasicAuthAssignment_9_2");
			builder.put(grammarAccess.getHTTPRequestAccess().getHeadersAssignment_10_2(), "rule__HTTPRequest__HeadersAssignment_10_2");
			builder.put(grammarAccess.getHTTPRequestAccess().getHeadersAssignment_10_3_1(), "rule__HTTPRequest__HeadersAssignment_10_3_1");
			builder.put(grammarAccess.getHTTPRequestAccess().getDataAssignment_11_2(), "rule__HTTPRequest__DataAssignment_11_2");
			builder.put(grammarAccess.getHTTPRequestAccess().getDataAssignment_11_3_1(), "rule__HTTPRequest__DataAssignment_11_3_1");
			builder.put(grammarAccess.getHTTPRequestAccess().getDataTypeAssignment_11_7(), "rule__HTTPRequest__DataTypeAssignment_11_7");
			builder.put(grammarAccess.getImageAccess().getNameAssignment_2(), "rule__Image__NameAssignment_2");
			builder.put(grammarAccess.getImageAccess().getURLAssignment_6(), "rule__Image__URLAssignment_6");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getLanguageAssignment_1_1(), "rule__TextLanguageInputHttpResponse__LanguageAssignment_1_1");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getInputsAssignment_3(), "rule__TextLanguageInputHttpResponse__InputsAssignment_3");
			builder.put(grammarAccess.getTextLanguageInputHttpResponseAccess().getInputsAssignment_4_1(), "rule__TextLanguageInputHttpResponse__InputsAssignment_4_1");
			builder.put(grammarAccess.getTextInputHttpResponseAccess().getTokensAssignment(), "rule__TextInputHttpResponse__TokensAssignment");
			builder.put(grammarAccess.getTextInputTextAccess().getTokensAssignment(), "rule__TextInputText__TokensAssignment");
			builder.put(grammarAccess.getKeyValueAccess().getKeyAssignment_0(), "rule__KeyValue__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValueAccess().getValueAssignment_2(), "rule__KeyValue__ValueAssignment_2");
			builder.put(grammarAccess.getDataAccess().getKeyAssignment_0(), "rule__Data__KeyAssignment_0");
			builder.put(grammarAccess.getDataAccess().getValueAssignment_2(), "rule__Data__ValueAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BotGrammarAccess grammarAccess;

	@Override
	protected InternalBotParser createParser() {
		InternalBotParser result = new InternalBotParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
