/**
 * generated by Xtext 2.23.0
 */
package org.xtext.botGenerator.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.botGenerator.services.BotGrammarAccess;

@SuppressWarnings("all")
public class BotFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private BotGrammarAccess _botGrammarAccess;
  
  protected void _format(final /* Bot */Object bot, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nAmbiguous feature call.\nThe extension methods\n\tprepend(ISemanticRegion, Procedure1<? super IHiddenRegionFormatter>) in IFormattableDocument and\n\t<T extends EObject> prepend(T, Procedure1<? super IHiddenRegionFormatter>) in IFormattableDocument\nboth match."
      + "\nThere is no context to infer the closure\'s argument types from. Consider typing the arguments or put the closures into a typed context."
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nforEach cannot be resolved"
      + "\nallRegionsFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nintents cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nentities cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nactions cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nflows cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* UserInteraction */Object flow, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nAmbiguous feature call.\nThe extension methods\n\tprepend(ISemanticRegion, Procedure1<? super IHiddenRegionFormatter>) in IFormattableDocument and\n\t<T extends EObject> prepend(T, Procedure1<? super IHiddenRegionFormatter>) in IFormattableDocument\nboth match."
      + "\nThere is no context to infer the closure\'s argument types from. Consider typing the arguments or put the closures into a typed context."
      + "\ntarget cannot be resolved"
      + "\n!== cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\noutcoming cannot be resolved"
      + "\nsize cannot be resolved"
      + "\n> cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nforEach cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\noutcoming cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* Action */Object action, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nText cannot be resolved to a type."
      + "\nText cannot be resolved to a type."
      + "\nImage cannot be resolved to a type."
      + "\nImage cannot be resolved to a type."
      + "\nImage cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPRequest cannot be resolved to a type."
      + "\nHTTPResponse cannot be resolved to a type."
      + "\nHTTPResponse cannot be resolved to a type."
      + "\nHTTPResponse cannot be resolved to a type."
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field indent is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field GeneratorPackage is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field GeneratorPackage is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\nprepend cannot be resolved"
      + "\ninterior cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nheaders cannot be resolved"
      + "\nsize cannot be resolved"
      + "\n> cannot be resolved"
      + "\nheaders cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nKEY_VALUE__KEY cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ndata cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ndata cannot be resolved"
      + "\nsize cannot be resolved"
      + "\n> cannot be resolved"
      + "\ndata cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nKEY_VALUE__KEY cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\n! cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeywords cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* TextLanguageInput */Object textLanInput, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nprepend cannot be resolved");
  }
  
  protected void _format(final /* Intent */Object intent, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method setNewLines(int, int, int) is undefined"
      + "\nThe method or field indent is undefined"
      + "\nThe method or field GeneratorPackage is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nprepend cannot be resolved"
      + "\ninterior cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nELEMENT__NAME cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nparameters cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nparameters cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* Entity */Object entity, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field indent is undefined"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ninterior cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* LanguageInput */Object lanInput, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nprepend cannot be resolved");
  }
  
  protected void _format(final /* Parameter */Object parameter, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nprepend cannot be resolved");
  }
  
  protected void _format(final /* IntentLanguageInputs */Object intentInput, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\ninputs cannot be resolved"
      + "\nprepend cannot be resolved");
  }
  
  public void format(final Object bot, final IFormattableDocument document) {
    if (bot instanceof XtextResource) {
      _format((XtextResource)bot, document);
      return;
    } else if (bot instanceof EObject) {
      _format((EObject)bot, document);
      return;
    } else if (bot == null) {
      _format((Void)null, document);
      return;
    } else if (bot != null) {
      _format(bot, document);
      return;
    } else if (bot != null) {
      _format(bot, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(bot, document).toString());
    }
  }
}
