/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator.generator;

import generator.Entity;
import generator.EntityInput;
import generator.Intent;
import generator.IntentInput;
import generator.IntentLanguageInputs;
import generator.LanguageInput;
import generator.RegexInput;
import generator.SimpleInput;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.xtext.botGenerator.generator.DialogflowGenerator;
import org.xtext.botGenerator.generator.RasaGenerator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class BotGenerator extends AbstractGenerator {
  public static final int REGEX = 0;
  
  public static final int SIMPLE = 1;
  
  public static final int COMPOSITE = 2;
  
  public static final int TRAINING = 3;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    DialogflowGenerator dialogflow = new DialogflowGenerator();
    dialogflow.doGenerate(resource, fsa, context);
    RasaGenerator rasa = new RasaGenerator();
    rasa.doGenerate(resource, fsa, context);
  }
  
  public static int entityType(final Entity entity) {
    LanguageInput input = entity.getInputs().get(0);
    EntityInput _get = input.getInputs().get(0);
    if ((_get instanceof RegexInput)) {
      return BotGenerator.REGEX;
    } else {
      EntityInput _get_1 = input.getInputs().get(0);
      if ((_get_1 instanceof SimpleInput)) {
        return BotGenerator.SIMPLE;
      } else {
        return BotGenerator.COMPOSITE;
      }
    }
  }
  
  public static int intentType(final Intent intent) {
    IntentLanguageInputs input = intent.getInputs().get(0);
    IntentInput _get = input.getInputs().get(0);
    if ((_get instanceof RegexInput)) {
      return BotGenerator.REGEX;
    } else {
      return BotGenerator.TRAINING;
    }
  }
}
